use_frameworks!

platform :ios, '10.0'

target 'GJStockListView_Example' do
  pod 'GJStockListView', :path => '../'
	pod 'MJRefresh',               '3.1.15.6'
  pod 'ReactiveObjC', 					'3.0.0'
pod 'MXSegmentedPager'
end
