use_frameworks!

platform :ios, '8.0'

target 'GJStockListView_Example' do
  pod 'GJStockListView', :path => '../'
	pod 'MJRefresh',               '3.1.15.6'

  target 'GJStockListView_Tests' do
    inherit! :search_paths

    
  end
end
